spring:
  application:
    name: gateway-server
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://config-server:8888/"
#spring:
#  application:
#    name: gateway-server
#  profiles:
#    active: local
#  config:
#    import: "optional:configserver:http://localhost:8888"