spring:
  application:
    name: restaurant-service
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://nyamnyam-config-server-7a2e1-100286202-d2ce4428f134.kr.lb.naverncp.com:8888"
#spring:
#  application:
#    name: restaurant-service
#  profiles:
#    active: local
#  config:
#    import: "optional:configserver:http://localhost:8888"